version: "3.7"

services:

## --------------------------- PIX TRANSFER --------------------------- ##

  pix-transfer:
    image: vicctim/pix-transfer-php:latest
    container_name: pix-transfer
    
    environment:
      - DB_HOST=pix-transfer-db
      - DB_NAME=upload_system
      - DB_USER=upload_user
      - DB_PASS=upload_password
      - SMTP_HOST=pix-transfer-mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=noreply@pixfilmes.com
      - SMTP_FROM_NAME=Pix Transfer
    
    volumes:
      - pix-transfer-uploads:/var/www/html/uploads
      - pix-transfer-logs:/var/www/html/logs
    
    networks:
      - minha-rede
    
    depends_on:
      - pix-transfer-db
      - pix-transfer-mailhog
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.pix-transfer.rule=Host(`transfer.victorsamuel.com.br`)
        - traefik.http.routers.pix-transfer.entrypoints=websecure
        - traefik.http.routers.pix-transfer.tls.certresolver=letsencryptresolver
        - traefik.http.services.pix-transfer.loadBalancer.server.port=80
        - traefik.http.routers.pix-transfer.service=pix-transfer
        - traefik.http.middlewares.pix-transfer-headers.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.pix-transfer-headers.headers.customrequestheaders.X-Forwarded-Host=transfer.victorsamuel.com.br
        - traefik.http.routers.pix-transfer.middlewares=pix-transfer-headers

## --------------------------- DATABASE --------------------------- ##

  pix-transfer-db:
    image: mysql:8.0
    container_name: pix-transfer-db
    
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=upload_system
      - MYSQL_USER=upload_user
      - MYSQL_PASSWORD=upload_password
    
    volumes:
      - pix-transfer-db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    
    networks:
      - minha-rede
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- MAILHOG --------------------------- ##

  pix-transfer-mailhog:
    image: mailhog/mailhog:latest
    container_name: pix-transfer-mailhog
    
    networks:
      - minha-rede
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.pix-transfer-mailhog.rule=Host(`mail.transfer.victorsamuel.com.br`)
        - traefik.http.routers.pix-transfer-mailhog.entrypoints=websecure
        - traefik.http.routers.pix-transfer-mailhog.tls.certresolver=letsencryptresolver
        - traefik.http.services.pix-transfer-mailhog.loadBalancer.server.port=8025
        - traefik.http.routers.pix-transfer-mailhog.service=pix-transfer-mailhog

## --------------------------- VOLUMES --------------------------- ##

volumes:
  pix-transfer-uploads:
    external: true
    name: pix-transfer-uploads
  pix-transfer-logs:
    external: true
    name: pix-transfer-logs
  pix-transfer-db-data:
    external: true
    name: pix-transfer-db-data

## --------------------------- NETWORKS --------------------------- ##

networks:
  minha-rede:
    external: true
    name: minha-rede 